# Generated by Django 4.0.2 on 2022-07-05 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('tipo_operacao', models.AutoField(primary_key=True, serialize=False)),
                ('desc_operacao', models.CharField(max_length=40, unique=True)),
                ('sinal_operacao', models.SmallIntegerField(choices=[(-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo')])),
            ],
            options={
                'verbose_name': 'TipoOperacao',
                'verbose_name_plural': 'TipoOperacoes',
            },
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=150)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('num_conselho', models.CharField(blank=True, max_length=10)),
                ('regiao_conselho', models.CharField(blank=True, max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=150)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('identidade', models.CharField(blank=True, max_length=40)),
                ('modo_pagamento', models.CharField(blank=True, max_length=15)),
                ('valor_padrao', models.FloatField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular_ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('celular_numero', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone_ddd', models.CharField(blank=True, max_length=3, null=True)),
                ('telefone_numero', models.CharField(blank=True, max_length=11, null=True)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('endereco', models.CharField(blank=True, max_length=60)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=40)),
                ('bairro', models.CharField(blank=True, max_length=60)),
                ('cidade', models.CharField(blank=True, max_length=60)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('paciente_responsavel', models.BooleanField(default=False)),
                ('nome_responsavel', models.CharField(blank=True, max_length=90)),
                ('cpf_responsavel', models.CharField(blank=True, max_length=11)),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular_ddd_responsavel', models.CharField(blank=True, max_length=3, null=True)),
                ('celular_numero_responsavel', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone_ddd_responsavel', models.CharField(blank=True, max_length=3, null=True)),
                ('telefone_numero_responsavel', models.CharField(blank=True, max_length=11, null=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(null=True)),
                ('valor_mov', models.FloatField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, max_length=120, null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('tipo_operacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipooperacao')),
            ],
        ),
    ]
