# Generated by Django 4.0.6 on 2022-07-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QryMovimentacao',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('data_hora', models.DateTimeField(null=True)),
                ('valor_mov', models.FloatField(blank=True, null=True)),
                ('bln_selecionado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'qry_Movimentacao',
                'managed': False,
            },
        ),
    ]
