# Generated by Django 4.0.6 on 2022-07-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentacao', 'verbose_name_plural': 'Movimentacoes'},
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='bln_selecionado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordem', models.DateTimeField(null=True)),
                ('data_pagamento', models.DateTimeField(null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
            options={
                'verbose_name': 'OrdemServico',
                'verbose_name_plural': 'OrdemServicos',
            },
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='ordem_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ordemservico'),
        ),
    ]
