# Generated by Django 4.0.2 on 2022-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='nome',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='sobrenome',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
