# Generated by Django 4.0.2 on 2022-02-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_terapeuta_nome_terapeuta_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapeuta',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='terapeuta',
            name='location',
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='apelido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
