# Generated by Django 4.0.6 on 2022-07-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_qrymovimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='QryListaOrdensServico',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('data_ordem', models.DateTimeField(null=True)),
                ('data_envio', models.DateTimeField(null=True)),
                ('nome', models.TextField(blank=True)),
                ('valor_total', models.FloatField(blank=True, null=True)),
                ('num_movimentos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qry_lista_ordens_servico',
                'managed': False,
            },
        ),
    ]
