# Generated by Django 4.0.2 on 2022-03-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_terapeuta_bio_remove_terapeuta_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('sobrenome', models.CharField(blank=True, max_length=150)),
                ('apelido', models.CharField(blank=True, max_length=50)),
                ('modo_pagamento', models.CharField(blank=True, max_length=15)),
                ('valor_padrao', models.FloatField(blank=True, default=None, null=True)),
                ('terapeuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta')),
            ],
        ),
    ]
