# Generated by Django 4.0.6 on 2022-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movimentacao_terapeuta_alter_qrymovimentacao_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QryMovimentacaoAgregada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terapeuta', models.PositiveBigIntegerField()),
                ('paciente', models.PositiveBigIntegerField()),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('valor_total', models.FloatField(blank=True, null=True)),
                ('num_movimentos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qry_movimentacao_agregada',
                'managed': False,
            },
        ),
    ]
