# Generated by Django 4.0.2 on 2022-03-02 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_adicao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
