# Generated by Django 4.0.2 on 2022-03-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paciente_data_adicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terapeuta'),
        ),
    ]
