# Generated by Django 4.0.6 on 2022-07-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ordemservico_terapeuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='terapeuta',
        ),
    ]
