# Generated by Django 4.0.2 on 2022-03-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paciente_bairro_paciente_cep_paciente_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='identidade',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='complemento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
