# Generated by Django 4.0.2 on 2022-03-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paciente_identidade_paciente_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
