# Generated by Django 4.0.2 on 2022-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paciente_cpf_responsavel_paciente_nome_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='paciente_responsavel',
            field=models.BooleanField(default=False),
        ),
    ]
