# Generated by Django 4.0.2 on 2022-03-11 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paciente_paciente_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='paciente_responsavel',
        ),
    ]
