# Generated by Django 4.0.2 on 2022-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_paciente_paciente_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='paciente_responsavel',
            field=models.BooleanField(default=False),
        ),
    ]
