# Generated by Django 4.0.2 on 2022-03-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_paciente_paciente_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data da operação')),
            ],
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='num_conselho',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='regiao_conselho',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
