# Generated by Django 4.0.2 on 2022-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_movimentacao_terapeuta_cpf_terapeuta_num_conselho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='valor_mov',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
