# Generated by Django 4.0.2 on 2022-03-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_movimentacao_data_hora_movimentacao_valor_mov'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
