# Generated by Django 4.0.2 on 2022-03-14 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_movimentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.PositiveSmallIntegerField(choices=[(0, 'Consulta'), (1, 'Pagamento')])),
                ('data_hora', models.DateTimeField(null=True, verbose_name='Data da operação')),
                ('valor_mov', models.FloatField(blank=True, null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
    ]
