# Generated by Django 4.0.2 on 2022-03-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_movimentacao_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='observacao',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
