# Generated by Django 4.0.2 on 2022-04-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_paciente_celular_ddd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data_hora',
            field=models.DateField(null=True),
        ),
    ]
