# Generated by Django 4.0.2 on 2022-04-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_movimentacao_data_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='data_hora',
            field=models.DateTimeField(null=True),
        ),
    ]
