# Generated by Django 4.0.2 on 2022-04-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_movimentacao_data_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('tipo_operacao', models.PositiveSmallIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('desc_operacao', models.TextField(max_length=40, unique=True)),
                ('sinal_operacao', models.SmallIntegerField(choices=[(-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo')])),
            ],
        ),
    ]
