# Generated by Django 4.0.2 on 2022-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tipooperacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipooperacao',
            name='tipo_operacao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
