# Generated by Django 4.0.2 on 2022-04-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_tipooperacao_tipo_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipooperacao',
            name='desc_operacao',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
