# Generated by Django 4.0.2 on 2022-04-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_tipooperacao_desc_operacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacao_1',
            fields=[
                ('tipo_operacao', models.AutoField(primary_key=True, serialize=False)),
                ('desc_operacao', models.CharField(max_length=40, unique=True)),
                ('sinal_operacao', models.SmallIntegerField(choices=[(-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo')])),
            ],
        ),
        migrations.DeleteModel(
            name='TipoOperacao',
        ),
    ]
