# Generated by Django 4.0.2 on 2022-04-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_tipooperacao_1_delete_tipooperacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('tipo_operacao', models.AutoField(primary_key=True, serialize=False)),
                ('desc_operacao', models.CharField(max_length=40, unique=True)),
                ('sinal_operacao', models.SmallIntegerField(choices=[(-1, 'Negativo'), (0, 'Neutro'), (1, 'Positivo')])),
            ],
            options={
                'verbose_name': 'TipoOperacao',
                'verbose_name_plural': 'TipoOperacoes',
            },
        ),
        migrations.DeleteModel(
            name='TipoOperacao_1',
        ),
    ]
