# Generated by Django 4.0.2 on 2022-04-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_tipooperacao_delete_tipooperacao_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_operacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipooperacao'),
        ),
    ]
