# Generated by Django 4.0.2 on 2022-04-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_movimentacao_tipo_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='celular_numero',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular_numero_responsavel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_numero',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone_numero_responsavel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
